### PR TITLE
Do not requre Clone for RefVal::map

### PR DESCRIPTION
**Pull request by stepancheg**

### CODE REVIEW

**Comment by d-e-s-o** [comment]
Oh, I guess I was too quick with my version bump. Anyway, merged with few minor changes. Thanks again!

**Comment by stepancheg** [comment]
Can you bump the version, please?

**Comment by d-e-s-o** [comment]
I'll release a new version tomorrow evening.

**Comment by d-e-s-o** [comment]
FYI, 0.1.7 is out now.

**Pull request closed without merging**
